plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
}

apply from: '../dependencies.gradle'
android {
    namespace 'com.example.moudle_web'
    dataBinding  {
        enabled = true
    }
}

dependencies {
    api project(':commonLibary')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}